version: "3.9"

services:
  main-api: 
    build: TwitterBook/
    restart: always
    ports: 
      - "7000:80"
    depends_on: 
      - sql-server-db

  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
    volumes:
      - sql-server-twitterbook-data:/var/opt/mssql/data
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "TwitterB00kDB"
      ACCEPT_EULA: "Y"

volumes:
  sql-server-twitterbook-data: